content:
  - type: collection
    label: "Blog Posts"
    name: "blog"
    path: "content/blog"
    fields:
      - { label: "Title", name: "title", type: "string" }
      - { label: "Publish Date", name: "date", type: "date" }
      - { label: "Description", name: "description", type: "string" }
      - { label: "Tags", name: "tags", type: "select"}
      - { label: "Body", name: "body", type: "rich-text" }
media:
  input: "static/images"
  output: "/images"