languageCode = 'en-gb'
title = 'Ian Ahuja'
disableKinds = ['taxonomy', 'term']
intro = true
headline = "Ian"
description = "Ian Ahuja's website"
baseURL = "https://ianahuja.com"
contentDir = "content"
github = "https://github.com/12ian34"
twitter = "https://x.com/12ian34"
email = "12ian34@example.com"
opengraph = true
shareTwitter = true
buildFuture = true
[markup]
  [markup.goldmark.renderer]
    unsafe = true
[params]
  blog_title = "words"
[permalinks]
  blog = "/blog/:year/:month/:slug/"
  supperclubs = "/supperclubs/:slug/"